settings:
  username: "tcitry"
  commit_msg: "Update the recent activity"
  max_lines: 100
  disabled_events: ["push"]
  url_text: "{REPO}{ID}"
  commit_name: "recent-activity-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
